[functions]
  node_bundler = "esbuild"

[build]
  edge_functions = "dist"

[dev]
  moduleResolution = "node"
  autoLaunch = false
  port = 8888
  targetPort = 3000
  publish = "dist"

[[edge_functions]]
  path = "/"
  function = "handler"
